In [1]:
import pandas as pd
import numpy as np

In [4]:
orginal_array=np.array([5,6,7,8,9])
ref_array=orginal_array
print(orginal_array)
print(ref_array)

[5 6 7 8 9]
[5 6 7 8 9]


In [6]:
### Now we can change the particular element in orginal array using assignment statement and check with orginal.
### The element has changed in both so both has same memory locations 

In [5]:
orginal_array[2]=4
print(orginal_array)
print(ref_array)

[5 6 4 8 9]
[5 6 4 8 9]


In [7]:
## Check wether the two reference is located with the same memory
   ## Method 1: Reference equality (is)
    ## Method 2:To test equality using id function
    

True


In [11]:
print(orginal_array is ref_array)
print(id(orginal_array))
print(id(ref_array))

True
140685690662320
140685690662320


In [1]:
old = [[1,3,5],[2,4,6]]
new = old

old[1][2] = 8

print("Old list:", old)
print("New list:", new)


Old list: [[1, 3, 5], [2, 4, 8]]
New list: [[1, 3, 5], [2, 4, 8]]
