In [10]:
import pandas as pd
import numpy as np
import copy

In [11]:
Orginal_array=np.array([10,20,30,40,50])
copied_array=copy.deepcopy(Orginal_array)
Orginal_array[0]=5
print(Orginal_array)
print(copied_array)
     

[ 5 20 30 40 50]
[10 20 30 40 50]


In [12]:
## Deep copy allocates object memory address in different location.

In [13]:
print(id(Orginal_array))
print(id(copied_array))

140270008623824
140270833714928


In [14]:
## Deep copy simply copy all the elements of original array, 
## if we made any changes in the copied items it wont affect the original items.

In [15]:
copied_array[1]=60

In [16]:
copied_array

array([10, 60, 30, 40, 50])

In [17]:
Orginal_array

array([ 5, 20, 30, 40, 50])

In [18]:
Orginal_array is copied_array

False

In [19]:
Orginal_array == copied_array

array([False, False,  True,  True,  True])

In [20]:
### I made changes to old i.e old[1][2]=8 and see only the old list is modified
### This means, both the old list and the new list are independent. 
### This is because Deep copy makes self-rule copy of the orginal item as well as all of its nested objects.

In [21]:


old = [[1,3,5],[2,4,6]]
new = copy.deepcopy(old)

old[1][2] = 8

print("Old list:", old)
print("New list:", new)



Old list: [[1, 3, 5], [2, 4, 8]]
New list: [[1, 3, 5], [2, 4, 6]]
