In [3]:
import numpy as np
import warnings 
warnings.filterwarnings('ignore')

## Creating Numpy Array

In [75]:
val=np.array([10,20,30,40,50])
val


array([10, 20, 30, 40, 50])

In [76]:
val.dtype

dtype('int64')

## Access elements of NumPy Array

In [77]:
val[1]

20

### Assign  value 

In [78]:
val[3]=60
val

array([10, 20, 30, 60, 50])

### Insert Item

In [79]:
# Insert the item using Index and Value
z = np.insert(val, 1, 70)
z

array([10, 70, 20, 30, 60, 50])

In [80]:
# Append the item by value
val = np.append(val, 80)
val

array([10, 20, 30, 60, 50, 80])

In [81]:
# Remove the item using Index
val = np.delete(val, 5)
val

array([10, 20, 30, 60, 50])

In [83]:
### Sorting Value
val=np.sort(val)
val

array([10, 20, 30, 50, 60])

#### Let's Assign Float Value

In [9]:
val[1]=20.5  #### NumPy only support same kind of data type so the val[1] remain same
val  

array([10, 20, 30, 60, 50])

In [10]:
### Float Data Type

In [11]:
val1=np.array([10.2,20.5,30.67,40.5])
val1

array([10.2 , 20.5 , 30.67, 40.5 ])

In [12]:
val1.dtype

dtype('float64')

# N Dimensional Array 

### one Dimensional Array 

In [13]:
one_D=np.array([99,88,77,66])
one_D

array([99, 88, 77, 66])

### Two Dimensional Array

In [17]:
two_D=np.array([[2,4,6,8],[3,6,9,12],[4,8,12,16]])
two_D

array([[ 2,  4,  6,  8],
       [ 3,  6,  9, 12],
       [ 4,  8, 12, 16]])

In [18]:
two_D.ndim

2

In [19]:
two_D.shape

(3, 4)

In [20]:
two_D.size

12

### Three Dimensional Array

In [23]:
three_D=np.array([
   [
    [1,2,3,4],
    [6,7,8,9]
],
   [
    
    [10,11,12,6],
    [13,14,15,16]
   ]
                 ])

three_D

array([[[ 1,  2,  3,  4],
        [ 6,  7,  8,  9]],

       [[10, 11, 12,  6],
        [13, 14, 15, 16]]])

In [24]:
three_D.ndim

3

In [25]:
three_D.size

16

In [26]:
three_D.shape

(2, 2, 4)

# Array from DataStructure

### Array from list

In [28]:
list_items=[2,4,6,8]
list_items

[2, 4, 6, 8]

In [29]:
array_list=np.array(list_items)
array_list

array([2, 4, 6, 8])

### Array from tuple

In [31]:
tuple_items=(3,9,11,13)
array_tuple=np.array(tuple_items)
array_tuple

array([ 3,  9, 11, 13])

# Intrincic Numpy Array Creation

### arange() will create array with regular incrementing values

In [4]:
x=np.arange(15)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [5]:
np.arange(2,10,dtype=np.float)

array([2., 3., 4., 5., 6., 7., 8., 9.])

In [39]:
y=np.arange(3,4,0.1)
y

array([3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8, 3.9])

### Linspace - Number of random values between the range


In [41]:
values=np.linspace(1,5)
values

array([1.        , 1.08163265, 1.16326531, 1.24489796, 1.32653061,
       1.40816327, 1.48979592, 1.57142857, 1.65306122, 1.73469388,
       1.81632653, 1.89795918, 1.97959184, 2.06122449, 2.14285714,
       2.2244898 , 2.30612245, 2.3877551 , 2.46938776, 2.55102041,
       2.63265306, 2.71428571, 2.79591837, 2.87755102, 2.95918367,
       3.04081633, 3.12244898, 3.20408163, 3.28571429, 3.36734694,
       3.44897959, 3.53061224, 3.6122449 , 3.69387755, 3.7755102 ,
       3.85714286, 3.93877551, 4.02040816, 4.10204082, 4.18367347,
       4.26530612, 4.34693878, 4.42857143, 4.51020408, 4.59183673,
       4.67346939, 4.75510204, 4.83673469, 4.91836735, 5.        ])

### Randint - Number of random integers between the range


In [42]:
# Random value between the range
items = np.random.randint(1, 10)
items

9

In [43]:
# How many random values between 0 to number
items = np.random.randint(1, 50, 6)
items

array([30, 16, 45, 10, 41, 49])

### Creating numpy array with fixes values

##### Zeros

In [44]:
x=np.zeros(3)
x

array([0., 0., 0.])

In [50]:
y=np.zeros((4,2))
y

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

##### Ones

In [51]:
val=np.ones(6)
val

array([1., 1., 1., 1., 1., 1.])

In [54]:
x=np.ones(3,dtype=int)
x

array([1, 1, 1])

##### Empty -Initialize array without values

In [56]:
items = np.empty(2) #### NOTE: Empty does not only gives zero. Sometimes some uninitialized array
items

array([2.05833592e-312, 2.33419537e-312])

##### Fill

In [58]:
items = np.empty(5)
items.fill(4)
items

array([4., 4., 4., 4., 4.])

##### Full

In [59]:
x = np.full(5, 4)
x

array([4, 4, 4, 4, 4])

In [64]:
y = np.full((5,3),6)
y

array([[6, 6, 6],
       [6, 6, 6],
       [6, 6, 6],
       [6, 6, 6],
       [6, 6, 6]])

## Reshape

###  reshape Gives a new shape to an array without changing its data

In [12]:
items=np.arange(1,25)
items

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [13]:
np.reshape(items, (4,6))


array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [14]:
np.reshape(items, (3, 4, 2))

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12],
        [13, 14],
        [15, 16]],

       [[17, 18],
        [19, 20],
        [21, 22],
        [23, 24]]])

In [15]:
np.reshape(items, 24)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

## Flatten

In [18]:
items = np.reshape(items, (3, 4, 2))
items

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12],
        [13, 14],
        [15, 16]],

       [[17, 18],
        [19, 20],
        [21, 22],
        [23, 24]]])

In [19]:
items_flat = items.flatten()
items_flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

## Ravel

In [20]:
items = np.reshape(items, (3, 4, 2))
items

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12],
        [13, 14],
        [15, 16]],

       [[17, 18],
        [19, 20],
        [21, 22],
        [23, 24]]])

In [21]:
items_ravel = items.ravel()
items_ravel

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [22]:
items_ravel[0]

1

In [25]:
items_ravel[0]=100
items_flat[0]=200

In [26]:
items, items_flat, items_ravel

(array([[[100,   2],
         [  3,   4],
         [  5,   6],
         [  7,   8]],
 
        [[  9,  10],
         [ 11,  12],
         [ 13,  14],
         [ 15,  16]],
 
        [[ 17,  18],
         [ 19,  20],
         [ 21,  22],
         [ 23,  24]]]),
 array([200,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
         14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24]),
 array([100,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
         14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24]))

In [27]:
##Ravel is the reference of original array, Any changes in ravel will affect original array
## Flatten is copy of original array, Any changes in flatten does not affect the original array
