In [1]:
import pandas as pd 
import numpy as np
import copy

In [2]:
## A shallow copy generate a new object which stores the reference of the original elements.

In [3]:
## Create a copy using shallow copy

In [8]:
original=np.array([1,3,5,7])
new=copy.copy(orginal)
print(orginal)
print(new)

[1 3 5 7]
[1 3 5 7]


In [9]:
## This means it will create new and independent object with same content.
## To verify this, we print the both old_list and new_list.

In [10]:
### Then we add the 9 into original. but this was not copied in new.

In [11]:
original=np.append(original,[9])
print(original)
print(new)

[1 3 5 7 9]
[1 3 5 7]


In [12]:
original=np.array([1,3,5,7])
new=copy.copy(original)
original[0]=2
print(original)
print(new)

[2 3 5 7]
[1 3 5 7]


In [13]:
print(id(original))
print(id(new))

140477800008560
140477800008080


In [14]:
orginal is new

False

In [15]:
## Adding new nested object using Shallow copy



In [16]:
import copy

old = [[1,3,5],[2,4,6]]
new = copy.copy(old)

old[1][1] = 8

print("Old list:", old)
print("New list:", new)
print(id(old))
print(id(new))

Old list: [[1, 3, 5], [2, 8, 6]]
New list: [[1, 3, 5], [2, 8, 6]]
140477551695168
140477551689408
